### ISSUE TITLE
Model not defined.

### ISSUE THREAD

**Issue by darylbleach** [raulrene/Twitter-ContestJS-bot#13]
Had this error arise when running node index.js

/opt/app/config.js:1
(function (exports, require, module, __filename, __dirname) { model.exports = {
                                                              ^

ReferenceError: model is not defined
    at Object.<anonymous> (/opt/app/config.js:1:63)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/app/api-functions.js:2:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/app/index.js:1:73)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by darylbleach** [comment]
Issue resolved
